---

- name: install prerequisite packages
  yum:
    name: "{{ item }}"
    state: latest
  loop:
  - "yum-utils"
  - "epel-release"

- name: "Install jq"
  yum:
    name: "jq"
    state: latest


- name: add repository for Docker CE
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo


- name: "Add Registry Mirror configuration"
  block:
  - name: "Create folder for keeping docker daemon configurations"
    file:
      path: "/etc/docker"
      state: "directory"

  - name: "Put configurations into remote folder"
    template:
      src: "templates/daemon.json"
      dest: "/etc/docker/daemon.json"
  when:
  - docker.registry_mirror is defined
  - docker.registry_mirror != ""


- name: install docker-ce
  yum:
    name: 'docker-ce'
    state: latest
  notify: restart docker.service


- name: Add specific users into Docker group
  user:
    name: '{{ item }}'
    shell: /bin/bash
    groups: docker
    append: yes
  with_items: '{{ docker.users }}'
  when:
  - docker.users is defined