
- name: install prerequisite packages
  yum:
    name: 'yum-utils'
    state: latest

- name: add repository for Docker CE
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: install docker-ce
  yum:
    name: 'docker-ce'
    state: latest
  notify: restart docker.service


- name: Add specific users into Docker group
  user:
    name: '{{ item }}'
    shell: /bin/bash
    groups: docker
    append: yes
  with_items: '{{ docker_users }}'
  when: docker.users|length > 0