---

- name: "Install prerequisite packages"
  apt:
    name: '{{ item }}'
    state: 'latest'
    update_cache: 'yes'
  loop:
    - 'apt-transport-https'
    - 'ca-certificates'
    - 'curl'
    - 'gnupg2'
    - 'software-properties-common'
    - 'jq'
  ignore_errors: yes


- name: "Import GPG key"
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    state: present


- name: "Add APT repository of Docker"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes
  ignore_errors: yes


- name: "Add Registry Mirror configuration"
  block:
  - name: "Create folder for keeping docker daemon configurations"
    file:
      path: "/etc/docker"
      state: "directory"

  - name: "Put configurations into remote folder"
    template:
      src: "templates/daemon.json"
      dest: "/etc/docker/daemon.json"
  when:
  - docker.registry_mirror is defined
  - docker.registry_mirror != ""


- name: "Install Docker CE"
  apt:
    name: 'docker-ce'
    state: 'latest'
    # update_cache: 'yes'
  notify: restart docker.service