---
# tasks file for ansible-role-docker


- include: '{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}.yml'
  

- name: Install docker-compose
  get_url:
    url: 'https://github.com/docker/compose/releases/download/1.11.2/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}'
    dest: /usr/local/bin/docker-compose
    mode: "a+x"
  when: ansible_virtualization_type != 'docker' and docker_install_composer