
- name: Install prerequisite packages
  apt:
    name: '{{ item }}'
    state: 'latest'
    update_cache: 'yes'
  with_items:
    - 'apt-transport-https'
    - 'ca-certificates'
    - 'curl'


- name: Import GPG key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present


- name: Add APT repository of Docker
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    update_cache: yes


- name: Install Docker CE
  apt:
    name: 'docker-ce'
    state: 'latest'
    update_cache: 'yes'
  notify: restart docker.service


- name: Add specific users into Docker group
  user:
    name: '{{ item }}'
    shell: /bin/bash
    groups: docker
    append: yes
  with_items: '{{ docker_users }}'
  when: docker.users|length > 0


# - name: Change docker-compose command to be executable
#   file:
#     path: /usr/local/bin/docker-compose
#     mode: "a+x"
#   when: ansible_virtualization_type != 'docker'

#- name: Configure docker defaults
#  copy:
#    content: "DOCKER_OPTS=\"{{ docker_opts }}\""
#    dest: /etc/default/docker
#    owner: root
#    group: root
#    mode: 0744
#  notify:
#    - reload docker
  
