---

- name: Install prerequisite packages
  apt:
    name: '{{ item }}'
    state: 'latest'
    update_cache: 'yes'
  with_items:
    - 'apt-transport-https'
    - 'ca-certificates'
    - 'curl'
    - 'software-properties-common'
    - 'jq'

- name: Install Docker CE
  apt:
    name: 'docker-io'
    state: 'latest'
    update_cache: 'yes'
  notify: restart docker.service


- name: Add specific users into Docker group
  user:
    name: '{{ item }}'
    shell: /bin/bash
    groups: docker
    append: yes
  with_items: '{{ docker.users }}'
  when:
  - docker.users is defined
